### ISSUE TITLE
arduino ide 1.6.4 retrieves older version of this library

### ISSUE THREAD

**Issue by rayjanwilson** [adafruit/Adafruit_TMP007_Library#2]
when i installed this today from within the library manager feature of arduino ide 1.6.4, it pulled in the version that depends on the Adafruit Unified Sensor, however the latest version of the library does not depend on the Unified Sensor library.

how do we go about updating the version the arduino ide points to?

**Comment by tdicola** [comment]
Oh thanks for catching that, looks like we need the latest release tagged and then Arduino's system will pick it up.  Just added the tag so it should be updated on their side in a few hours.  Thanks again for raising the issue!

**Comment by rayjanwilson** [comment]
Awesome thanks. Glad it was an easy fix 😃
